chrome update

diff --git a/.github/workflows/6-scheduled-production-worker.yaml b/.github/workflows/6-scheduled-production-worker.yaml
--- a/.github/workflows/6-scheduled-production-worker.yaml
+++ b/.github/workflows/6-scheduled-production-worker.yaml
@@ -37,10 +37,18 @@ jobs:
           # Install Google Chrome
           wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
           sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get -f install -y
+          
           # Install ChromeDriver
           CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
-          CHROMEDRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
-          wget https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip
+          echo "Installing ChromeDriver for Chrome version: $CHROME_VERSION"
+          CHROMEDRIVER_VERSION=$(curl -sS "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION%.*}")
+          
+          if [ -z "$CHROMEDRIVER_VERSION" ]; then
+            echo "ChromeDriver version not found for Chrome version $CHROME_VERSION"
+            exit 1
+          fi
+          
+          wget "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
           unzip chromedriver_linux64.zip
           sudo mv chromedriver /usr/bin/chromedriver
           sudo chmod +x /usr/bin/chromedriver
